name: gitsbites
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.0.1
  pdf: ^3.11.2
  path_provider: ^2.1.1
  universal_html: ^2.2.4  # ✅ Add this for Web support
  printing: ^5.14.0
  firebase_storage: ^12.4.1
  intl: ^0.18.0
  table_calendar: ^3.0.0
  fluttertoast: ^8.2.12
  image_picker: ^0.8.4+8
  razorpay_flutter: ^1.3.4
  flutter_svg: ^2.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/profile_pic.png
    - assets/puttu.png
    - assets/appam.png
    - assets/chapati.png
    - assets/logog.png
    - assets/Logog.png
    - assets/visa.jpg
    - assets/chickencurry.png
    - assets/eggcurry.png
    - assets/idli.png
    - assets/kadalacurry.png
    - assets/porotta.png
    - assets/meals.png
    - assets/biriyani.png
    - assets/fishfry.png


