name: gitsbites
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.0.1
  pdf: ^3.11.2
  path_provider: ^2.1.1
  universal_html: ^2.2.4  # ✅ Add this for Web support
  printing: ^5.14.0
  firebase_storage: ^12.4.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/profile_pic.png
    - assets/item1.png
    - assets/item2.png
    - assets/item3.png
    - assets/logog.png
    - assets/visa.jpg
    - assets/item4.png
    - assets/item6.png
    - assets/item5.png
    - assets/item7.png
    - assets/item8.png
    - assets/item9.png



